version: 2.1

executors:
  linux:
    docker:
      - image: cimg/base:2022.04
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
  macos:
    macos:
      xcode: 13

orbs:
  node: circleci/node@5.0.2
  win: circleci/windows@4.1.1

jobs:
  test-unix:
    parameters:
      os:
        type: executor
      node-version:
        type: string
    executor: << parameters.os >>
    steps:
      - checkout
      - node/install:
          node-version: << parameters.node-version >>
      - run:
          name: Configure NPM Token
          command: npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
      - node/install-packages:
          cache-path: node_modules
      - run:
          name: Run Tests
          command: npm run test:ci
  test-windows:
    parameters:
      node-version:
        type: string
    executor: win/default
    steps:
      - checkout
      - run:
          name: Install Node
          command: |
            nvm install --lts << parameters.node-version >>
            nvm use << parameters.node-version >>
      - run:
          name: Configure NPM Token
          command: npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
      - run:
          name: Install packages
          command: npm ci
      - run:
          name: Run Tests
          command: npm run test:ci
  test-e2e:
    parameters:
      os:
        type: executor
      node-version:
        type: string
    executor: << parameters.os >>
    steps:
      - checkout
      - node/install:
          node-version: << parameters.node-version >>
      - run:
          name: Configure NPM Token
          command: npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
      - node/install-packages:
          cache-path: node_modules
      - run:
          name: Run E2E Tests
          command: npm run test:e2e:ci
  test-coverage:
    parameters:
      os:
        type: executor
      node-version:
        type: string
    executor: << parameters.os >>
    steps:
      - checkout
      - node/install:
          node-version: << parameters.node-version >>
      - run:
          name: Configure NPM Token
          command: npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
      - node/install-packages:
          cache-path: node_modules
      - run:
          name: Generate Coverage Report
          command: npm run coverage
      - store_artifacts:
          path: coverage



workflows:
  version: 2
  test:
    jobs:
      - test-unix:
          context:
            - particle-ci-private
          matrix:
            parameters:
              os: [linux, macos]
              node-version: ["10", "12", "14", "16"]
      - test-windows:
          context:
            - particle-ci-private
          matrix:
            parameters:
              node-version: ["10", "12", "14", "16"]
      - test-e2e:
          name: test-e2e-linux
          context:
            - particle-ci-private
          matrix:
            parameters:
              os: [linux]
              node-version: ["12"]
      - test-e2e:
          name: test-e2e-macos
          requires:
            - test-e2e-linux
          context:
            - particle-ci-private
          matrix:
            parameters:
              os: [macos]
              node-version: ["12"]
      - test-coverage:
          context:
            - particle-ci-private
          matrix:
            parameters:
              os: [linux]
              node-version: ["12"]

